%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Data\2022_01_ADNI_timeSeries\ADNI_ATN_info.xlsx
%    Worksheet: Foglio1
%
% Auto-generated by MATLAB on 31-Oct-2022 11:38:28

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 16);

% Specify sheet and range
opts.Sheet = "Foglio1";
opts.DataRange = "A2:P492";

% Specify column names and types
opts.VariableNames = ["ID", "RID", "ADNIMERGE", "ACQUISITIONDATE", "AGE", "SEX", "ABETA", "TAU", "PTAU", "A_COMPOSITE_SUVR", "T_COMPOSITE_SUVR", "F_NORM_MEAN", "N_HIPPOCAMPUS_VOLUME", "N_AMYGDALA_VOLUME", "N_CTX_ENTORHINAL_VOLUME", "N_CTX_CAUDALMIDDLEFRONTAL_VOLUME"];
opts.VariableTypes = ["string", "double", "categorical", "datetime", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "ID", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["ID", "ADNIMERGE", "SEX"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "ACQUISITIONDATE", "InputFormat", "");

% Import the data
ADNIATNinfo1 = readtable("C:\Data\2022_01_ADNI_timeSeries\ADNI_ATN_info.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts