function ADNIMERGESept2022 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ADNIMERGESEPT2022 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  ADNIMERGESEPT2022 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  ADNIMERGESept2022 = importfile("C:\Users\jtess\Downloads\ADNIMERGE_Sept2022.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 23-Sep-2022 15:17:33

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 116);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["RID", "COLPROT", "ORIGPROT", "PTID", "SITE", "VISCODE", "EXAMDATE", "DX_bl", "AGE", "PTGENDER", "PTEDUCAT", "PTETHCAT", "PTRACCAT", "PTMARRY", "APOE4", "FDG", "PIB", "AV45", "FBB", "ABETA", "TAU", "PTAU", "CDRSB", "ADAS11", "ADAS13", "ADASQ4", "MMSE", "RAVLT_immediate", "RAVLT_learning", "RAVLT_forgetting", "RAVLT_perc_forgetting", "LDELTOTAL", "DIGITSCOR", "TRABSCOR", "FAQ", "MOCA", "EcogPtMem", "EcogPtLang", "EcogPtVisspat", "EcogPtPlan", "EcogPtOrgan", "EcogPtDivatt", "EcogPtTotal", "EcogSPMem", "EcogSPLang", "EcogSPVisspat", "EcogSPPlan", "EcogSPOrgan", "EcogSPDivatt", "EcogSPTotal", "FLDSTRENG", "FSVERSION", "IMAGEUID", "Ventricles", "Hippocampus", "WholeBrain", "Entorhinal", "Fusiform", "MidTemp", "ICV", "DX", "mPACCdigit", "mPACCtrailsB", "EXAMDATE_bl", "CDRSB_bl", "ADAS11_bl", "ADAS13_bl", "ADASQ4_bl", "MMSE_bl", "RAVLT_immediate_bl", "RAVLT_learning_bl", "RAVLT_forgetting_bl", "RAVLT_perc_forgetting_bl", "LDELTOTAL_BL", "DIGITSCOR_bl", "TRABSCOR_bl", "FAQ_bl", "mPACCdigit_bl", "mPACCtrailsB_bl", "FLDSTRENG_bl", "FSVERSION_bl", "IMAGEUID_bl", "Ventricles_bl", "Hippocampus_bl", "WholeBrain_bl", "Entorhinal_bl", "Fusiform_bl", "MidTemp_bl", "ICV_bl", "MOCA_bl", "EcogPtMem_bl", "EcogPtLang_bl", "EcogPtVisspat_bl", "EcogPtPlan_bl", "EcogPtOrgan_bl", "EcogPtDivatt_bl", "EcogPtTotal_bl", "EcogSPMem_bl", "EcogSPLang_bl", "EcogSPVisspat_bl", "EcogSPPlan_bl", "EcogSPOrgan_bl", "EcogSPDivatt_bl", "EcogSPTotal_bl", "ABETA_bl", "TAU_bl", "PTAU_bl", "FDG_bl", "PIB_bl", "AV45_bl", "FBB_bl", "Years_bl", "Month_bl", "Month", "M", "update_stamp"];
opts.VariableTypes = ["double", "categorical", "categorical", "categorical", "double", "double", "datetime", "categorical", "double", "categorical", "double", "categorical", "categorical", "categorical", "double", "double", "string", "double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "double", "double", "datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "double", "string", "double", "double", "double", "double", "datetime"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["PIB", "FBB", "PIB_bl", "FBB_bl"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["PTID", "DX_bl", "PTGENDER", "PTETHCAT", "PTRACCAT", "PTMARRY", "PIB", "FBB", "DX", "PIB_bl", "FBB_bl"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "EXAMDATE", "InputFormat", "dd/MM/yy");
opts = setvaropts(opts, "EXAMDATE_bl", "InputFormat", "dd/MM/yy");
opts = setvaropts(opts, "update_stamp", "InputFormat", "yyyy-MM-dd HH:mm:ss.SSS");
opts = setvaropts(opts, ["VISCODE", "FLDSTRENG", "FSVERSION", "FLDSTRENG_bl", "FSVERSION_bl"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["VISCODE", "FLDSTRENG", "FSVERSION", "FLDSTRENG_bl", "FSVERSION_bl"], "ThousandsSeparator", ",");

% Import the data
ADNIMERGESept2022 = readtable(filename, opts);

end