function ADNIdatasummary02052022 = importfile2(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  ADNIDATASUMMARY02052022 = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  ADNIDATASUMMARY02052022 = IMPORTFILE(FILE, SHEET) reads from the
%  specified worksheet.
%
%  ADNIDATASUMMARY02052022 = IMPORTFILE(FILE, SHEET, DATALINES) reads
%  from the specified worksheet for the specified row interval(s).
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  ADNIdatasummary02052022 = importfile("C:\Data\2022_01_ADNI_timeSeries\ADNI_data_summary_02-05-2022.xlsx", "ADNI3", [2, 1045]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 23-Sep-2022 15:31:59

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 1045];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 32);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":AF" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["ID", "DATABASE", "STUDYGROUP", "ADNIMERGE", "ACQUISITIONDATE", "AGE", "SEX", "DOWNLOAD", "T1PREPROCESSING", "FREESURFER", "SULCI", "FMRIPREPROCESSING", "FUNCTIONALCONNECTIVITY", "FCGRAPHS", "DMRIPREPROCESSING", "DTIFITTING", "TBSS", "STRUCTURALCONNECTIVITY", "GENETICS", "PRS", "DIGASSCATInADNI3", "DIGASSCATInADNI1", "DIGASSCATInADNI2", "DIGASSCATInWGS", "UEANCESTRY", "OriginalIndex", "MBAcquisition", "IssuesInFMRIData", "IssuesInDMRIData", "VarName30", "VarName31", "VarName32"];
opts.VariableTypes = ["string", "categorical", "categorical", "categorical", "datetime", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "string", "string"];

% Specify variable properties
opts = setvaropts(opts, ["ID", "VarName30", "VarName31", "VarName32"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["ID", "DATABASE", "STUDYGROUP", "ADNIMERGE", "SEX", "VarName30", "VarName31", "VarName32"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "ACQUISITIONDATE", "InputFormat", "");

% Import the data
ADNIdatasummary02052022 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":AF" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    ADNIdatasummary02052022 = [ADNIdatasummary02052022; tb]; %#ok<AGROW>
end

end